# Generated by Django 5.2.6 on 2025-10-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
