# Generated by Django 5.2.6 on 2025-10-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_variation_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
