# Generated by Django 5.2.6 on 2025-12-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='l_name',
        ),
    ]
