# Generated by Django 5.2.6 on 2025-12-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_first_name_order_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Order',
            new_name='order',
        ),
    ]
